### PR TITLE
Specify target-os also for 32-bit build.

### PR DESCRIPTION
**Pull request by kasper93**
Little change to improve compatibility.

### CODE REVIEW

**Comment by Nevcairiel** [comment]
What does this actually change in the build?

**Comment by kasper93** [comment]
This specify target os in ffmpeg configure. Since we want mingw32 hence this change. The problem is that MSYS2 by default is recognized as `MSYS_NT-6.3` and it fails. With MSYS1 it was MINGW32*.

But in fact it depends on MSYSTEM value and standard way is to specify it when needed. So I changed my patch.

**Comment by Nevcairiel** [comment]
Sounds like something that should be fixed in ffmpeg configure instead, target-os should not be required for a plain and simple compilation, its only there for x64 because its a kind-of cross-compilation.

**Comment by Nevcairiel** [comment]
Like this:
https://gist.github.com/Nevcairiel/6b84875ff2ca03d1234e

**Comment by kasper93** [comment]
I was thinking about it, but I wasn't sure. We can have both 64-bit and 32-bit MSYS and it can have it own gcc which will act more like cygwin one as opposed to mingw one which is native. I have basic setup only with core MSYS2 and your toolset and this works fine. 

I agree this should be fixed in config if possible. I guess you could try sending this patch to ffmpeg and we will see if they agree.

I'm closing this PR.

**Comment by Nevcairiel** [comment]
I downloaded a MSYS2 env just now to test my patch and it works with my own GCC. Not sure how its integrated GCC would differ, but its still a mingw gcc, so I think the patch should be fine.

Send it to the ffmpeg ML in any case.

**Comment by nak5124** [comment]
if your MSYSTEM was MSYS, you might start bash with msys2.bat.
MSYSTEM=MSYS is for building MSYS apps not MINGW* ones.
You should start bash with mingw32.bat (for 32bit) or mingw64.bat (for 64bit).
mingw32.bat sets MSYSTEM=MINGW32, mingw64 MSYSTEM=MINGW64.
If you can't be bothered to use separate batch files, you can use a simple shell script to change MSYSTEM and PATH like this (https://gist.github.com/eca418486d605e236af1.git).
anyway, for 64bit, MSYS2 sets MSYSTEM=MINGW64, so we need to change ffmpeg configure like this (https://gist.github.com/bf24e2f70d408b98ce1b.git).

**Comment by Nevcairiel** [comment]
More reasons to stick to MSYS1 then, just calling sh.exe or bash.exe should "just work".

**Comment by kasper93** [comment]
I understand that much, but we execute scripts directly. `sh build_ffmpeg.sh` form batch file. Hence MSYSTEM variable is not set and MSYS2 defaults to MSYS. Hence this change https://github.com/kasper93/LAVFilters/commit/398e01efcd8a0ad710432a746dd52229c7ec426b

I don't know if we can change ffmpeg configure to make it work also with MSYS. Like I said before. 

I don't know if ffmpeg configure can work for use ;p

**Comment by kasper93** [comment]
> More reasons to stick to MSYS1 then, just calling sh.exe or bash.exe should "just work".

Depends how you look at it. MSYS and MINGW are different things and they cover this with MSYSTEM env variable which we can set according to our needs.

**Pull request closed without merging**
