### PR TITLE
CDecWMV9MFT: Fix heap memory corruption when destroying Buffer struct.

### PR DESCRIPTION
**Pull request by kasper93**
Raw pointers to interface is never good idea.
Also simplify the code a little.

### CODE REVIEW

**Comment by Nevcairiel** [comment]
I don't use smart pointers anywhere in my code and I don't really want to start now.

**Comment by kasper93** [comment]
Fair enough. Updated with proper fix.

**Comment by Nevcairiel** [comment]
Analyzers gets confused by this because they are dumb, compilers on the other hand do not know about the other struct since its not in the include tree. I have never observed any problems in the generated code.

**Comment by Nevcairiel** [comment]
Pushed nevertheless with a slightly reworded message.

**Comment by kasper93** [comment]
Main point here is to make LAV not disturb debugging is VS. It is annoying when you have sample and VS throws at you run-time errors from lav ;)

**Pull request closed without merging**
