### PR TITLE
build_ffmpeg.sh: Do not copy dcadec files when not needed.

### PR DESCRIPTION
**Pull request by kasper93**
- Use pushd/popd

Hi, 

Few more or less cosmetic changes so we won't diverge too much in our mpc-hc's script. I hope it is fine. I wasn't sure about naming, because most names are lowercase with `_` and some new ones are UPPERCASE without `_`. Tell me which way do you prefer. Also if you fell pushd/popd change is not needed I will remove it.

### CODE REVIEW

**Comment by Nevcairiel** [comment]
This change seems to add a lot of unneeded complexity to the build script, I don't like it.

**Comment by kasper93** [comment]
I've removed pushd change which was unnecessary idea. Now it is much simpler, if you still don't like it I will close this PR.

**Comment by Nevcairiel** [comment]
If you're trying to prevent re-linking dcadec, wouldn't it be better to suggest adding the "-p" flag the install calls in the dcadec Makefile? Doing that solves any relinking for me, as make acts on the timestamps when linking.

**Comment by kasper93** [comment]
In theory using `-p` will prerve timestamps also when they shouldn't be. `-C` flag is the one to use, but it is not available on older install.

**Comment by kasper93** [comment]
I have splitted changes into two commits. First is purely cosmetic and second is functional for dcadec.Tell me if any of it could go into repo if you don't like them, please close PR.

**Comment by Nevcairiel** [comment]
I cherry-picked one of the changes, but I rather like using the install-lib target, as it makes sure only public headers are ever in the include path, and leaves all the management to the dcadec Makefile without hacking around some special cases. Plus I like having a central pkgconfig dir, as I have been thinking about changing some of the other binary libs to be compiled on demand and installed there.

And to be honest, the rebuilding thing isn't even a case that occurs with LAV.
For all I care, i could set dcadec to simply never rebuild if I use "quick" mode, as I only use quick when hacking on ffmpeg, not to speed up build times for release builds, as I don't trust incremental builds that much.

**Pull request closed without merging**
