### PR TITLE
Add compilation flags for better code generation.

### PR DESCRIPTION
**Pull request by kasper93**
- Enable LTCG for better devirtualization and code optimization.
- Do not use TR namespace for already supported features in standard
library
- Enable /Gw (Optimize Global Data)
- Use 3 iterantions for COMDAT folding as it gives noticable improvment
over default two iterations.
- Add /Zc:referenceBinding,strictStrings,ternary to enforce C++ standard
conformant code. Fix few minor issues in the code.

### CODE REVIEW

**Comment by Nevcairiel** [comment]
LTCG is already enabled (in every projects file in the Configuration PropertyGroup, global override didn't work), using the compiler and lib/linker flags is not recommended in favor of that method (it sets all relevant things)

**Comment by Nevcairiel** [comment]
I split a changes into individual commits, but left the /Zc stuff and most of the code changes out, since it didn't actually build.

**Comment by kasper93** [comment]
> LTCG is already enabled (in every projects file in the Configuration PropertyGroup, global override didn't work)

Right, I missed that it is set in projects. I did see improvement, but maybe other options contributed to the result. But setting property in common.props works just fine (I validated it), not sure why it didn't work for you. As common.props is just included there so it should just work. Anyway I removed it from the patch. It might be cleaner to have it defined in one place, but having it in project works too. 

>  using the compiler and lib/linker flags is not recommended in favor of that method (it sets all relevant things)

Ok.

> I split a changes into individual commits, but left the /Zc stuff and most of the code changes out, since it didn't actually build.

strictStrings failed, I've removed it. It would need quite a lot minor changed here and there. Sorry for insufficient testing.

> Also, I skipped the compiler settings that are actually the default in O2 builds (ie. string pooling and inlines)

Sure. 

---

I've uploaded patch with /Zc:referenceBinding,ternary and /stdc++latest. The later might not be interesting for you, but I still recommend it as Microsoft really invest in STL and best experience comes with latest mode. Other are provided mostly because many deprecated things were removed, hence the option to bring them back.

**Comment by Nevcairiel** [comment]
I've merged the remaining changes minus the /std:c++latest change, since it causes some warning spam from ffmpeg headers (which are C and not C++, but not like the compiler cares for the difference)

**Pull request closed without merging**
