### PR TITLE
Use av_find_best_stream for video stream selection

### LINKED ISSUE #416: DASH Manifest stream selection
There are some issues with playback of DASH Manifests from YouTube. URL extracted with youtube-dl.

First issue is that there are multiple video streams that are flagged as default. LAV selects the first one. Preferably it should pick the one with best quality.
dash_example

Another issue is that sound goes mute after a few seconds. It comes back after a seek.

Finally, it can contain both H264 and VP9 streams. Switching format does not work well.

### PR DESCRIPTION
**Pull request by kasper93**
Fixes #416

### CODE REVIEW

**Comment by Nevcairiel** [comment]
This feels like it might cause quite some regressions especially with the special cases it was designed to avoid.

**Comment by kasper93** [comment]
* One workaround that would be reverted is this one https://github.com/Nevcairiel/LAVFilters/commit/cc5d58fd87ce52f5cfce81249f2506c096641a8f although I would like for bitrate check to be reinstated. 
* More recently added change https://github.com/Nevcairiel/LAVFilters/commit/cc7af2cd2f3faa7fb2346904896a8764fb8cade1 is also taken into account as `av_find_best_stream` selects stream with most frames.

Rest of the logic looks similar and ffmpeg's one looks robust.

Up to you to decide, I can send patch to fix default disposition selection in old code if you prefer less intrusive change.

**Comment by ale5000-git** [comment]
There may be an use case for both selection algoritms, so what about put a settings in the UI to choose it at runtime?

**Comment by clsid2** [comment]
According to MKVToolNix v58 changelog, the Matroska spec has recently been adapted to allow flagging multiple tracks of same type as Default.

**Comment by Nevcairiel** [comment]
I'll look into revisiting this entire logic for the next bigger update, perhaps using the ffmpeg function.
For now I have added a default check to account for multiple default streams.

**Pull request closed without merging**
