### PR TITLE
HLS: Select program with higher bitrate if video resolution in the same

### PR DESCRIPTION
**Pull request by kasper93**

### CODE REVIEW

**Comment by ale5000-git** [comment]
It is possible that there is same resolution and different formats, in this case it is also possible that a better format give more quality with lower bitrate.

I think that the only case worth comparing the bitrate is when both resolution and format match.

**Comment by Nevcairiel** [comment]
There is a reason the variant_bitrate is used, even if not particularly good of a measure, its still an approximation in absence of better information. Many variable-bitrate codecs, especially audio (eg. AAC) do not provide any other measure, and this is used to select the highest quality variant - for example in BBC Radio streams.

**Comment by kasper93** [comment]
> I think that the only case worth comparing the bitrate is when both resolution and format match.

It is not really feasible to do universally, you wound need to calculate weighted bitrate based on codec and parameters, it is not always obvious. And in practice it is not very common to have higher bitrate, lower quality variant. 
 
> There is a reason the variant_bitrate is used, even if not particularly good of a measure, its still an approximation in absence of better information. Many variable-bitrate codecs, especially audio (eg. AAC) do not provide any other measure, and this is used to select the highest quality variant - for example in BBC Radio streams.

Are you responding to my changes or his comment? Because I'm confused. variant_bitrate will be the same for all streams in given program, so stream selection will not do anything, or am I missing a case here?

**Comment by Nevcairiel** [comment]
Merged manually with a different change for the variant bitrate

**Pull request closed without merging**
